### ISSUE TITLE
Trying to use 0.0.14dev0 on Linux

### ISSUE THREAD

**Issue by killamonis** [facebookresearch/xformers#658] opened 2023-01-29 18:42 UTC
# ❓ Questions and Help
I've been trying to install xformers 0.0.14dev0 so I can use the dreambooth extension on automatic1111 following this tutorial https://www.youtube.com/watch?v=O01BrQwOd-Q 
and using the tar.gz file here https://github.com/facebookresearch/xformers/issues/650

but I'm getting error "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vd4d0v97/xformers/version.py'" when trying to run `pip install -U -I --no-deps https://github.com/C43H66N12012S2/stable-diffusion-webui/releases/download/torch13/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl`

Any idea how I can go about successfully installing this version of xformers?

**Comment by danthe3rd** [comment] 2023-01-30 11:57
Duplicate of https://github.com/facebookresearch/xformers/issues/650

**Closed by danthe3rd** 2023-01-30 11:57 UTC
