### ISSUE TITLE
performance of swiglu operator

### ISSUE THREAD

**Issue by yingtongxiong** [facebookresearch/xformers#734] opened 2023-04-27 06:31 UTC
# ❓ Questions and Help
Hello, I have tested the performance of swiglu operator with two different implementation(One is yours, the other is implemented by using pytorch). However, I found that the implementation of xformers is quiet slower than mine. Of course, I believe that the implementation in xformers is highly optimized. Therefore, I am very confused about this phenomenon. Do you have any comments or suggestions?

The following is my test code:

```python
import torch
from torch.nn import functional as F
from torch import nn

from xformers.ops import swiglu, SwiGLU
from xformers.ops.swiglu_op import SwiGLUFusedOp
import numpy as np

class SwiGLU_Pytorch(nn.Module):
    
    def __init__(self, w1, w2, w3) -> None:
        super().__init__()
        self.w1 = w1
        self.w2 = w2
        self.w3 = w3
    
    def forward(self, x):
        x1 = F.linear(x, self.w1.weight, self.w1.bias)
        x2 = F.linear(x, self.w2.weight, self.w2.bias)
        hidden = F.silu(x1) * x2
        return F.linear(hidden, self.w3.weight, self.w3.bias)
def main():
    
    shape = (9456, 1536, 2736)
    in_features = shape[1]
    hidden_features = shape[2]
    out_features = shape[1]
    bias = True
    repeats = 1000
    
    dtype = torch.float32
    device = 'cuda'
    
    l1 = nn.Linear(in_features, hidden_features, bias=bias).to(device).to(dtype)
    l2 = nn.Linear(in_features, hidden_features, bias=bias).to(device).to(dtype)
    l3 = nn.Linear(hidden_features, out_features, bias=bias).to(device).to(dtype)
    
    x_pt = torch.randn(shape[:2], dtype=dtype, device=device)
    x = x_pt.detach().clone().requires_grad_()
    
    assert torch.allclose(x_pt, x)
    
    model_pt = SwiGLU_Pytorch(l1, l2, l3).to(device=device, dtype=dtype)
    model = SwiGLU(in_features, hidden_features, out_features, bias, _pack_weights=False).to(device=device, dtype=dtype)
    
    with torch.no_grad():
        model.w1.weight.copy_(l1.weight)
        model.w1.bias.copy_(l1.bias)
        model.w2.weight.copy_(l2.weight)
        model.w2.bias.copy_(l2.bias)
        model.w3.weight.copy_(l3.weight)
        model.w3.bias.copy_(l3.bias)
    
    global loss
    # warm up
    for _ in range(20):
        _ = model_pt(x_pt)
        _ = model(x)
        loss = torch.randn_like(_) / 32
   
    with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA], record_shapes=True) as prof:
        with torch.profiler.record_function("pytorch model"):
            output_pt = model_pt(x_pt)
            output_pt.backward(loss)
    print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
    
    with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA], record_shapes=True) as prof:
        with torch.profiler.record_function("xformers model"):
            output = model(x)
            output.backward(loss)
    print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
    
    starter = torch.cuda.Event(enable_timing=True)
    ender = torch.cuda.Event(enable_timing=True)
    
    time_pt = np.zeros((repeats, 1))
    time_xf = np.zeros((repeats, 1))
    
    for rep in range(repeats):
        starter.record()
        _ = model_pt(x_pt)
        _.backward(loss)
        ender.record()
        torch.cuda.synchronize()
        time_pt[rep] = starter.elapsed_time(ender)
        
    torch.cuda.synchronize()
    for rep in range(repeats):
        starter.record()
        _ = model(x)
        _.backward(loss)
        ender.record()
        torch.cuda.synchronize()
        time_xf[rep] = starter.elapsed_time(ender)
        
    print("cuda event pytorch time = ", np.sum(time_pt) / repeats)
    print("cuda event xformers time = ", np.sum(time_xf) / repeats)
```

code above uses two measurement tools, and it seems that the results from these two tools shows that swiglu in xformers is more slower than mine.

**Comment by danthe3rd** [comment] 2023-04-27 06:42
Hi,
Thanks for posting this issue. A few things:
(1) xFormer's SwiGLU is optimized for f16/bf16 data types - it looks like you are running in f32
(2) you shouldn't set "_pack_weights=False" as it prevents from using the optimized kernel during the BW pass
I hope this helps!

**Comment by yingtongxiong** [comment] 2023-04-27 07:10
Sorry, I have pasted the wrong code to you. I actually tested the f16 and it shows the same results. Thank you very much, maybe I should set the "_pack_weights=True". However, when I call the function swiglu in xformers/xformers/ops/swiglu_op.py(Line 313) to instead the class SwiGLU, I still found that the xformers' swiglu is slower than mine.


my own implemented code:
class SwiGLU_Pytorch(nn.Module):
&nbsp; &nbsp; 
&nbsp; &nbsp; def __init__(self, w1, w2, w3) -&gt; None:
&nbsp; &nbsp; &nbsp; &nbsp; super().__init__()
&nbsp; &nbsp; &nbsp; &nbsp; self.w1 = w1
&nbsp; &nbsp; &nbsp; &nbsp; self.w2 = w2
&nbsp; &nbsp; &nbsp; &nbsp; self.w3 = w3
&nbsp; &nbsp; 
&nbsp; &nbsp; def forward(self, x):
&nbsp; &nbsp; &nbsp; &nbsp; x1 = F.linear(x, self.w1.weight, self.w1.bias)
&nbsp; &nbsp; &nbsp; &nbsp; x2 = F.linear(x, self.w2.weight, self.w2.bias)
&nbsp; &nbsp; &nbsp; &nbsp; hidden = F.silu(x1) * x2
&nbsp; &nbsp; &nbsp; &nbsp; return F.linear(hidden, self.w3.weight, self.w3.bias)



And I found that the forward function in SwiGLU is swiglu. Maybe the optimization of backward is not applied in function swiglu?
&nbsp;


974106207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matthias ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [facebookresearch/xformers] performance of swiglu operator (Issue #734)





 
Hi,
 Thanks for posting this issue. A few things:
 (1) xFormer's SwiGLU is optimized for f16/bf16 data types - it looks like you are running in f32
 (2) you shouldn't set "_pack_weights=False" as it prevents from using the optimized kernel during the BW pass
 I hope this helps!

**Comment by danthe3rd** [comment] 2023-04-27 07:28
Can you share the measurements you get, and the GPU you are using?

**Comment by yingtongxiong** [comment] 2023-04-27 07:33
974106207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/xformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/xformers] performance of swiglu operator (Issue #734)





 
Can you share the measurements you get, and the GPU you are using?

**Comment by yingtongxiong** [comment] 2023-04-27 07:40
This is my code:
import torch
from torch.nn import functional as F
from torch import nn

from xformers.ops import swiglu, SwiGLU
from xformers.ops.swiglu_op import SwiGLUFusedOp
from utils import benchmark_forward, benchmark_backward, benchmark_combined
import numpy as np
import copy

torch.manual_seed(0)

class SwiGLU_Pytorch(nn.Module):
&nbsp; &nbsp; 
&nbsp; &nbsp; def __init__(self, in_features, hidden_features, out_features, bias) -&gt; None:
&nbsp; &nbsp; &nbsp; &nbsp; super().__init__()
&nbsp; &nbsp; &nbsp; &nbsp; # self.w1 = w1
&nbsp; &nbsp; &nbsp; &nbsp; # self.w2 = w2
&nbsp; &nbsp; &nbsp; &nbsp; # self.w3 = w3
&nbsp; &nbsp; &nbsp; &nbsp; self.w1 = torch.nn.Linear(in_features, hidden_features, bias)
&nbsp; &nbsp; &nbsp; &nbsp; self.w2 = torch.nn.Linear(in_features, hidden_features, bias)
&nbsp; &nbsp; &nbsp; &nbsp; self.w3 = torch.nn.Linear(hidden_features, out_features, bias)
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; 
&nbsp; &nbsp; def forward(self, x):
&nbsp; &nbsp; &nbsp; &nbsp; x1 = F.linear(x, self.w1.weight, self.w1.bias)
&nbsp; &nbsp; &nbsp; &nbsp; x2 = F.linear(x, self.w2.weight, self.w2.bias)
&nbsp; &nbsp; &nbsp; &nbsp; hidden = F.silu(x1) * x2
&nbsp; &nbsp; &nbsp; &nbsp; return F.linear(hidden, self.w3.weight, self.w3.bias)

def main():
&nbsp; &nbsp; 
&nbsp; &nbsp; shape = (9456, 1536, 2736)
&nbsp; &nbsp; in_features = shape[1]
&nbsp; &nbsp; hidden_features = shape[2]
&nbsp; &nbsp; out_features = shape[1]
&nbsp; &nbsp; bias = True
&nbsp; &nbsp; repeats = 1000
&nbsp; &nbsp; 
&nbsp; &nbsp; dtype = torch.float16
&nbsp; &nbsp; device = 'cuda'
&nbsp; &nbsp; 
&nbsp; &nbsp; x_pt = torch.randn(shape[:2], dtype=dtype, device=device)
&nbsp; &nbsp; x = x_pt.detach().clone().requires_grad_()
&nbsp; &nbsp; 
&nbsp; &nbsp; assert torch.allclose(x_pt, x)

&nbsp; &nbsp; model_pt = SwiGLU_Pytorch(in_features, hidden_features, out_features, bias).to(device=device, dtype=dtype)
&nbsp; &nbsp; model = SwiGLU(in_features, hidden_features, out_features, bias, _pack_weights=True).to(device=device, dtype=dtype)
&nbsp; &nbsp; 
&nbsp; &nbsp; 
&nbsp; &nbsp; with torch.no_grad():
&nbsp; &nbsp; &nbsp; &nbsp; weights = model._ordered_params()
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w1.weight.copy_(weights[0])
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w1.bias.copy_(weights[1])
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w2.weight.copy_(weights[2])
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w2.bias.copy_(weights[3])
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w3.weight.copy_(weights[4])
&nbsp; &nbsp; &nbsp; &nbsp; model_pt.w3.bias.copy_(weights[5])
&nbsp; &nbsp; 
&nbsp; &nbsp; # global loss
&nbsp; &nbsp; # warm up
&nbsp; &nbsp; for _ in range(20):
&nbsp; &nbsp; &nbsp; &nbsp; _ = model_pt(x_pt)
&nbsp; &nbsp; &nbsp; &nbsp; loss = torch.randn_like(_) / 32
&nbsp; &nbsp; 
&nbsp; &nbsp; # using torch profiler
&nbsp; &nbsp; with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA], record_shapes=True) as prof:
&nbsp; &nbsp; &nbsp; &nbsp; with torch.profiler.record_function("pytorch model"):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; output_pt = model_pt(x_pt)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; output_pt.backward(loss)
&nbsp; &nbsp; print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
&nbsp; &nbsp; 
&nbsp; &nbsp; with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA], record_shapes=True) as prof:
&nbsp; &nbsp; &nbsp; &nbsp; with torch.profiler.record_function("xformers model"):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; output = model(x)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; output.backward(loss)
&nbsp; &nbsp; print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
&nbsp; &nbsp; 
&nbsp; &nbsp; 
&nbsp; &nbsp; # using cuda Event
&nbsp; &nbsp; starter = torch.cuda.Event(enable_timing=True)
&nbsp; &nbsp; ender = torch.cuda.Event(enable_timing=True)
&nbsp; &nbsp; 
&nbsp; &nbsp; time_pt = np.zeros((repeats, 1))
&nbsp; &nbsp; time_xf = np.zeros((repeats, 1))
&nbsp; &nbsp; 
&nbsp; &nbsp; for rep in range(repeats):
&nbsp; &nbsp; &nbsp; &nbsp; starter.record()
&nbsp; &nbsp; &nbsp; &nbsp; _ = model_pt(x_pt)
&nbsp; &nbsp; &nbsp; &nbsp; _.backward(loss)
&nbsp; &nbsp; &nbsp; &nbsp; ender.record()
&nbsp; &nbsp; &nbsp; &nbsp; torch.cuda.synchronize()
&nbsp; &nbsp; &nbsp; &nbsp; time_pt[rep] = starter.elapsed_time(ender)
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; torch.cuda.synchronize()
&nbsp; &nbsp; for rep in range(repeats):
&nbsp; &nbsp; &nbsp; &nbsp; starter.record()
&nbsp; &nbsp; &nbsp; &nbsp; _ = model(x)
&nbsp; &nbsp; &nbsp; &nbsp; _.backward(loss)
&nbsp; &nbsp; &nbsp; &nbsp; ender.record()
&nbsp; &nbsp; &nbsp; &nbsp; torch.cuda.synchronize()
&nbsp; &nbsp; &nbsp; &nbsp; time_xf[rep] = starter.elapsed_time(ender)
&nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; print("cuda event pytorch time = ", np.sum(time_pt) / repeats)
&nbsp; &nbsp; print("cuda event xformers time = ", np.sum(time_xf) / repeats)


if __name__ == '__main__':
    main()




The measurement results:



And My GPU is Nvidia A100(80GB), Thank you


974106207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/xformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/xformers] performance of swiglu operator (Issue #734)





 
Can you share the measurements you get, and the GPU you are using?

**Comment by danthe3rd** [comment] 2023-04-27 08:24
> The measurement results:

I see this section is empty?

**Comment by yingtongxiong** [comment] 2023-04-27 08:29
Sorry, it is really wired. I paste the screen shot in the attachment.





The GPU is Nvidia A100.


974106207
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/xformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/xformers] performance of swiglu operator (Issue #734)





  
The measurement results:
  
I see this section is empty?

**Comment by danthe3rd** [comment] 2023-04-27 08:35
This is still empty, I believe it's because you are sending it through emails

**Comment by yingtongxiong** [comment] 2023-04-27 08:38
I am very sorry.
<img width="725" alt="捕获" src="https://user-images.githubusercontent.com/45058324/234807458-ec787d14-8ca2-47cf-bb35-8451380e45c1.PNG">

Now, can you see it?

**Comment by danthe3rd** [comment] 2023-04-27 13:02
Thanks! I can see the numbers and managed to reproduce. For these shapes, the FW is still faster than PyTorch, but the backward is significatively slower indeed.

**Comment by yingtongxiong** [comment] 2023-04-28 02:42
Thank you very much. I have solved it. However, I wonder that the difference between the class SwiGLU and the function swiglu as I found that the class SwiGLU is faster than swiglu. are the optimization for backward in class SwiGLU also applied in the function swiglu?

**Comment by danthe3rd** [comment] 2023-04-28 07:50
The SwiGLU class just [calls](https://github.com/facebookresearch/xformers/blob/main/xformers/ops/swiglu_op.py#L440) the SwiGLU function. The only difference is that the SwiGLU class will ensure the weights for the first 2 linear layers are packed - and this enables some more optimizations in the BW pass.
So you should get the same performance with the function if you pack the weights.

**Comment by yingtongxiong** [comment] 2023-04-28 07:54
What if I call swiglu function directly? I notice that the interface of function swiglu does not have packed weights.
<img width="345" alt="捕获" src="https://user-images.githubusercontent.com/45058324/235088655-d0c7b978-dd42-4730-a98e-1c56d48d0706.PNG">

As you can see, I still have to transform the w1, w2 respectivly. Therefore, I am very confused about how to use packed weights in this function.

**Comment by danthe3rd** [comment] 2023-04-28 07:57
You need to have a single tensor that contains `w1` and `w2`, and then use xformer's `unbind` function to split the single merged weight into `w1` and `w2`. Then the `swiglu` function will recognize that the 2 weights are packed by looking at the tensor address in memory.
You can look at how it's done in the SwiGLU class:
https://github.com/facebookresearch/xformers/blob/b184fcf6e219c22958735f52c8531439258ac247/xformers/ops/swiglu_op.py#L447-L456

**Comment by yingtongxiong** [comment] 2023-04-28 07:59
Okay, Thank you very much.

**Closed** 2023-05-02 16:14 UTC

**Comment by ipoletaev** [comment] 2023-05-10 17:23
I have a few related questions on the same topic:

- what is the reason of not storing the entire set of weights in one matrix `torch.nn.Linear(ndim, 3 * hidden_dim)` and then `view()` its weights as needed in runtime? Is it slower / more expensive than having two separate matrices? 
- while using this op on torch 2.0.0 and xformers 0.0.19 I keep seeing 

```
.../.venv/lib/python3.8/site-packages/xformers/ops/unbind.py:46: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage_data_ptr = tensors[0].storage().data_ptr()
 ```
   is that all right?

**Comment by danthe3rd** [comment] 2023-05-10 17:47
You can ignore the warning, that's something we have to fix but minor.

You mean to store the 3 linears in a single tensor? Yeah that should be doable, but does not bring any performance benefit tho, so we don't require it to be more flexible
